name: Check broken links

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 9 * * 1'  # cada lunes a las 9am UTC

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/mlc_config.json'
